### ISSUE TITLE
Feature: Sound at Ring Controller when dialled Ring by OC

### ISSUE THREAD

**Issue by TheRedCreations** [MineDragonCZ/JSGMod-1.12.2#142]
![grafik](https://user-images.githubusercontent.com/35812887/164972103-ee4d14ec-9d83-48a6-8352-5bdd391c87e4.png)

let the computer press the buttons for you :)

**Comment by TheRedCreations** [comment]
I'll try to code it myself. I I don't succeed illl say it here.

**Comment by TheRedCreations** [comment]
See #144 comment

**Comment by MineDragonCZ** [comment]
Added
