### ISSUE TITLE
Bug: No limit in the Pegasus DHD while dialing

### ISSUE THREAD

**Issue by parofe01** [MineDragonCZ/JSGMod-1.12.2#160]
**Describe the bug**
When you dial the Pegasus DHD you are available to push more than 9 glyphs with no limit

**To Reproduce**
Try to dial a 15 glyphs adress in a Pegasus Gate with the Pegasus DHD

**Expected behavior**
Tecnically I'm not be available to dial a +9 adress but I can 

**Screenshots**
![image](https://user-images.githubusercontent.com/91995845/169043714-a149c86e-a02d-46c3-9a7d-9ee9f79819b9.png)

**Mod version**
Version of mod you are using. (aunis-1.12.2-4.10.1.0)

**Additional context**

**Comment by Fredyman95** [comment]
Known bug for more then 3 version...
