### ISSUE TITLE
Bug: OpenComputers. Weird results from "stargate.dialedAddress()" for incoming wormholes.

### ISSUE THREAD

**Issue by SAlexW** [MineDragonCZ/JSGMod-1.12.2#164]
![test](https://user-images.githubusercontent.com/38391381/170842957-5dd78a25-0003-40a9-b00b-1c17e41d4199.png)
To test the functionality of the "stargate.dialedAddress()" function, I built several gates, 3 of which I connected to the same computer. For the purity of the experiment, all these 3 gates were of different types.
These are shown in the screenshot:
The 1st line: the program itself in OC. The "gates" array stores the component address of the gate.
The 2nd and following lines: the result of the program. In each line, the first is the gate type for the incoming wormhole, then the gate status, and last is the result of the "dialedAddress" function.

For outgoing wormholes everything works fine, but for incoming ones the results were very strange:
1. The address is shown only while the gate is in the "unstable" state. That is, it was expected that when a wormhole was opened, this function would transmit the address of the gate on the other side immediately from the moment the gate was opened and continuously, even after the wormhole had stabilized. In practice, however, this is not the case. Judging by the results of the experiment, this function does not always give the address immediately after the wormhole is opened (this can be put down to a delay in the program itself or the entire MC). But, more strangely, after the wormhole is stabilized, this function gives "nil", even though the gate address on the other side was expected.
2. Even if you catch the moment with correct address output, the received address will correspond to the type of gate with an outgoing wormhole, although the PoO will be the same as the gate with an incoming wormhole. This looks pretty cheater, since it lets you immediately determine the type of gate on the other side without any problems, but it makes it a bit harder to programmatically process the results, since you additionally need to determine which glyph group the received address belongs to.

Suggested ways to solve this problem:
1. Extend the "dialedAddress" function for gates with incoming wormholes, to give the address of the gate on the other side after the connection is stabilized, and also change the result so that this function gives an address for a gate with an incoming wormhole instead of one with an outgoing wormhole, as is currently implemented.
2. Redo the function so that it works only for outgoing connections, and for incoming connections, give a result like "incoming connection, unable to determine address".

**Comment by SAlexW** [comment]
I almost forgot. AUNIS version: 4.10.1.0.

**Comment by MR-Spagetty** [comment]
The dialedAddress method should not show the address of the gate an incoming wormhole is coming from as that breaks away from cannon where there is no way to tell where an incoming wormhole is coming from

**Comment by MR-Spagetty** [comment]
Oops only read the first bit of suggesting how to fix it

**Comment by MR-Spagetty** [comment]
But should definately use solution 2 to stick with cannon
