### ISSUE TITLE
OpenComputers: (get energy)

### ISSUE THREAD

**Issue by JPr874** [MineDragonCZ/JSGMod-1.12.2#173]
When i went to dial the get with Open computers it came up with a code that said get_energy.

**Comment by kungstoffe08** [comment]
and are you sure your gate have enough power? that could be a possible reason

**Comment by MineDragonCZ** [comment]
> When i went to dial the get with Open computers it came up with a code that said get_energy.

Can you please send here your program? If its too long, please upload it on, for example, pastebin :)
Thanks.

**Comment by JPr874** [comment]
However it do it on another world. So two world using ags I had that problem.

**Comment by MineDragonCZ** [comment]
AGS problem
